module Stylesheet
  DECLARATIONS = %w{
    alignment_baseline
    background
    background_attachment
    background_clip
    background_color
    background_image
    background_origin
    background_position
    background_position_x
    background_position_y
    background_repeat
    background_repeat_x
    background_repeat_y
    background_size
    baseline_shift
    border
    border_bottom
    border_bottom_color
    border_bottom_left_radius
    border_bottom_right_radius
    border_bottom_style
    border_bottom_width
    border_collapse
    border_color
    border_image
    border_image_outset
    border_image_repeat
    border_image_slice
    border_image_source
    border_image_width
    border_left
    border_left_color
    border_left_style
    border_left_width
    border_radius
    border_right
    border_right_color
    border_right_style
    border_right_width
    border_spacing
    border_style
    border_top
    border_top_color
    border_top_left_radius
    border_top_right_radius
    border_top_style
    border_top_width
    border_width
    bottom
    box_shadow
    box_sizing
    caption_side
    clear
    clip
    clip_path
    clip_rule
    color
    color_interpolation
    color_interpolation_filters
    color_profile
    color_rendering
    content
    counter_increment
    counter_reset
    cursor
    direction
    display
    dominant_baseline
    empty_cells
    enable_background
    fill
    fill_opacity
    fill_rule
    filter
    float
    flood_color
    flood_opacity
    font
    font_family
    font_size
    font_stretch
    font_style
    font_variant
    font_weight
    glyph_orientation_horizontal
    glyph_orientation_vertical
    height
    image_rendering
    kerning
    left
    letter_spacing
    lighting_color
    line_height
    list_style
    list_style_image
    list_style_position
    list_style_type
    margin
    margin_bottom
    margin_left
    margin_right
    margin_top
    marker
    marker_end
    marker_mid
    marker_start
    mask
    mask_type
    max_height
    max_width
    min_height
    min_width
    opacity
    orphans
    outline
    outline_color
    outline_offset
    outline_style
    outline_width
    overflow
    overflow_wrap
    overflow_x
    overflow_y
    padding
    padding_bottom
    padding_left
    padding_right
    padding_top
    page
    page_break_after
    page_break_before
    page_break_inside
    pointer_events
    position
    quotes
    resize
    right
    shape_rendering
    size
    speak
    src
    stop_color
    stop_opacity
    stroke
    stroke_dasharray
    stroke_dashoffset
    stroke_linecap
    stroke_linejoin
    stroke_miterlimit
    stroke_opacity
    stroke_width
    tab_size
    table_layout
    text_align
    text_anchor
    text_decoration
    text_indent
    text_line_through
    text_line_through_color
    text_line_through_mode
    text_line_through_style
    text_line_through_width
    text_overflow
    text_overline
    text_overline_color
    text_overline_mode
    text_overline_style
    text_overline_width
    text_rendering
    text_shadow
    text_transform
    text_underline
    text_underline_color
    text_underline_mode
    text_underline_style
    text_underline_width
    top
    transition
    transition_delay
    transition_duration
    transition_property
    transition_timing_function
    unicode_bidi
    unicode_range
    vector_effect
    vertical_align
    visibility
    white_space
    widows
    width
    word_break
    word_spacing
    word_wrap
    writing_mode
    z_index
    zoom
  }
end